#cloud-config
packages:
   - nginx
   - sudo
   - python
   - ansible
users:
  - default
  - name: ansible
    groups: 
    - sudo
    - ansible
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOB/UqmPhWAcfzKyFbLeZMQsbBVF9tJJfpUHuDbfQUqqEN1fzT7JSIWk/C+kSyuE0TVTbzMd88CCyowKIPDzYJoPvx3QToSn72eX9GTAl4lM+IAx3Rw9AacYIPr2kxdVLzWdHRB8tgpe3ZmZtlFQSQVc69RQszBn6FzdY96Sqkv9gh977CcejXtYIRF2qEYE24BphGXZgJoBaKWnYm6Fj8hB2fy0dBr+gQ2HtkjRgNSJ52/UvDnNuv7jE50mBHYmwxiY/J9r6M+Va/BPsrYwcjyteyHBfPOq1vaUFBflC60+cG2D4VtW7SbV9lwZhDYi5ppxyLNcMCIzNmyWQDBxQ7oRS67T5qwCAk/oSZhNq2jf5gSnJ6mOg+6vl7pdiMY+7xTUJZAuMPvNJbd6m0ntySbJdxXeqdyaytH/CZoASJQwumYdzmsjAEAe/+l4Mrs8puSUyMzRbCc1Jdg7OlawW8AWU5sbVBdbU9imunTF81eba6FaN+wOiKi1+iV4cbJo0= anaelg@DELL-XPS


